In [3]:
%pip uninstall -y nwac

Found existing installation: nwac 0.1.0
Uninstalling nwac-0.1.0:
  Successfully uninstalled nwac-0.1.0
Note: you may need to restart the kernel to use updated packages.

In [4]:
%pip install -e .

Obtaining file:///Users/jake.sherman/Documents/nwac
Requirement already satisfied: pandas in /Users/jake.sherman/opt/anaconda3/lib/python3.8/site-packages (from nwac==0.1.0) (1.2.4)
Requirement already satisfied: python-dateutil>=2.7.3 in /Users/jake.sherman/opt/anaconda3/lib/python3.8/site-packages (from pandas->nwac==0.1.0) (2.8.1)
Requirement already satisfied: pytz>=2017.3 in /Users/jake.sherman/opt/anaconda3/lib/python3.8/site-packages (from pandas->nwac==0.1.0) (2021.1)
Requirement already satisfied: numpy>=1.16.5 in /Users/jake.sherman/opt/anaconda3/lib/python3.8/site-packages (from pandas->nwac==0.1.0) (1.19.5)
Requirement already satisfied: six>=1.5 in /Users/jake.sherman/opt/anaconda3/lib/python3.8/site-packages (from python-dateutil>=2.7.3->pandas->nwac==0.1.0) (1.15.0)
Installing collected packages: nwac
  Running setup.py develop for nwac
Successfully installed nwac
Note: you may need to restart the kernel to use updated packages.

In [5]:
from nwac import stations, download_historical_data

In [6]:
stations()

,Station_Id,Name,Elevation,Location,Start_Date
0,1,Alpental Base,3100,Snoqualmie Pass,2014-10-11
1,2,Alpental Mid-Mountain,4350,Snoqualmie Pass,2014-12-04
2,3,Alpental Summit,5470,Snoqualmie Pass,2014-01-03
3,4,Hurricane Ridge,5250,Olympics,2014-09-23
4,5,Mt Baker - Heather Meadows,4210,Mt Baker,2014-09-23
5,6,Mt Baker - Pan Dome,5020,Mt Baker,2014-09-23
6,7,Mazama,2170,Washington Pass,2014-01-01
7,8,Washington Pass Base,5450,Washington Pass,2014-09-23
8,9,Washington Pass Upper,6680,Washington Pass,2014-09-23
9,10,Dirty Face Summit,5980,Lake Wenatchee - Mission Ridge,2014-09-23
10,11,Lake Wenatchee,1930,Lake Wenatchee - Mission Ridge,2014-09-23
11,12,Berne Snow Camp,2700,Mt Baker,2014-09-23
12,13,Stevens Pass - Schmidt Haus,3950,Stevens Pass,2014-09-23
13,14,Stevens Pass - Grace Lakes,4800,Stevens Pass,2014-11-28
14,17,Stevens Pass - Skyline,5250,Stevens Pass,2014-12-23
15,18,Stevens Pass - Skyline,5250,Stevens Pass,2014-12-17
16,19,Tumwater Mountain,4180,Lake Wenatchee - Mission Ridge,2014-09-23
17,20,Mt Washington,4340,Snoqualmie Pass,2014-08-01
18,21,Snoqualmie Pass,3010,Snoqualmie Pass,2014-08-01
19,22,Snoqualmie Pass - Dodge Ridge,3760,Snoqualmie Pass,2014-08-01
20,23,Snoqualmie Pass - East Shed,3770,Snoqualmie Pass,2014-08-01
21,24,Mission Ridge Base,4610,Lake Wenatchee - Mission Ridge,2014-01-01
22,25,Mission Ridge Summit,6730,Lake Wenatchee - Mission Ridge,2014-09-23
23,26,Mission Ridge Mid-Mountain,5160,Lake Wenatchee - Mission Ridge,2014-09-23
24,27,Crystal Green Valley,6230,Mt Rainier,2015-01-12
25,28,Crystal Base,4570,Mt Rainier,2014-09-23
26,29,Crystal Summit,6830,Mt Rainier,2014-02-02
27,30,Sunrise Upper,6880,Mt Rainier,2014-09-23
28,31,Sunrise Base,6410,Mt Rainier,2014-04-05
29,32,Chinook Pass Summit,6240,Mt Rainier,2014-09-23
30,33,Chinook Pass Base,5500,Mt Rainier,2014-09-23
31,34,Camp Muir,10110,Mt Rainier,2014-09-23
32,35,Paradise,5400,Mt Rainier,2014-09-23
33,36,Paradise Wind,5380,Mt Rainier,2014-09-23
34,37,White Pass Base,4470,White Pass,2020-10-14
35,39,White Pass Upper,5800,White Pass,2014-09-23
36,40,Mt St Helens - Coldwater,3260,Mt St Helens,2014-09-23
37,41,Mt Hood Meadows Cascade Express,7300,Mt Hood,2014-01-03
38,42,Mt Hood Meadows Blue,6540,Mt Hood,2014-09-23
39,43,Mt Hood Meadows Base,5380,Mt Hood,2014-09-23
40,44,Timberline Lodge,5880,Mt Hood,2014-09-23
41,45,Timberline Magic Mile,6990,Mt Hood,2014-09-23
42,46,Ski Bowl Base,3660,Mt Hood,2014-10-30
43,47,Ski Bowl Summit,5010,Mt Hood,2015-01-08
44,48,Blewett Pass,4100,Lake Wenatchee - Mission Ridge,2014-10-22
45,49,White Pass Pigtail Peak,5970,White Pass,2014-09-23
46,50,Stevens Pass - Brooks,4800,Stevens Pass,2015-11-26

In [8]:
hurricane_ridge_2022_1 = download_historical_data(
    station_ids=[4],
    years=[2021, 2022]
)

hurricane_ridge_2022_1

,Station_Id,Station_Name,Date_Time,Battery_Voltage,Temp,Relative_Humidity,Precipitation,Total_Snow_Depth,Wind_Direction,Wind_Speed_Avg,...,Solar_Radiation,Snow_24_Hour,Intermittent_Shot_Snow,Net_Solar,Soil_Moisture_A,Soil_Moisture_B,Soil_Moisture_C,Soil_Temp_A,Soil_Temp_B,Soil_Temp_C
0,4,Hurricane Ridge,2021-12-31 23:00:00,13.2,7.331,82.1,0.0,234.10,352.00,1.373,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4,Hurricane Ridge,2021-12-31 22:00:00,13.2,5.482,83.1,0.0,234.10,19.83,0.816,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4,Hurricane Ridge,2021-12-31 21:00:00,13.2,5.383,82.0,0.0,234.10,48.91,0.375,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,Hurricane Ridge,2021-12-31 20:00:00,13.2,5.132,83.7,0.0,234.10,358.60,1.047,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,Hurricane Ridge,2021-12-31 19:00:00,13.2,4.706,81.6,0.0,53.59,53.13,0.015,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6131,4,Hurricane Ridge,2022-01-01 04:00:00,13.2,11.170,80.3,0.0,234.10,224.40,2.058,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6132,4,Hurricane Ridge,2022-01-01 03:00:00,13.2,11.290,82.9,0.0,234.10,247.70,0.205,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6133,4,Hurricane Ridge,2022-01-01 02:00:00,13.2,10.640,83.1,0.0,234.10,253.30,0.017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6134,4,Hurricane Ridge,2022-01-01 01:00:00,13.2,9.210,83.9,0.0,234.10,317.30,1.842,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6135,4,Hurricane Ridge,2022-01-01 00:00:00,13.2,8.160,81.6,0.0,234.10,334.70,0.423,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
hurricane_ridge_2022_2 = download_historical_data(
    station_names=["Hurricane Ridge"],
    years=[2021, 2022]
)

hurricane_ridge_2022_2

,Station_Id,Station_Name,Date_Time,Battery_Voltage,Temp,Relative_Humidity,Precipitation,Total_Snow_Depth,Wind_Direction,Wind_Speed_Avg,...,Solar_Radiation,Snow_24_Hour,Intermittent_Shot_Snow,Net_Solar,Soil_Moisture_A,Soil_Moisture_B,Soil_Moisture_C,Soil_Temp_A,Soil_Temp_B,Soil_Temp_C
0,4,Hurricane Ridge,2021-12-31 23:00:00,13.2,7.331,82.1,0.0,234.10,352.00,1.373,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4,Hurricane Ridge,2021-12-31 22:00:00,13.2,5.482,83.1,0.0,234.10,19.83,0.816,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4,Hurricane Ridge,2021-12-31 21:00:00,13.2,5.383,82.0,0.0,234.10,48.91,0.375,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,Hurricane Ridge,2021-12-31 20:00:00,13.2,5.132,83.7,0.0,234.10,358.60,1.047,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,Hurricane Ridge,2021-12-31 19:00:00,13.2,4.706,81.6,0.0,53.59,53.13,0.015,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6131,4,Hurricane Ridge,2022-01-01 04:00:00,13.2,11.170,80.3,0.0,234.10,224.40,2.058,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6132,4,Hurricane Ridge,2022-01-01 03:00:00,13.2,11.290,82.9,0.0,234.10,247.70,0.205,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6133,4,Hurricane Ridge,2022-01-01 02:00:00,13.2,10.640,83.1,0.0,234.10,253.30,0.017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6134,4,Hurricane Ridge,2022-01-01 01:00:00,13.2,9.210,83.9,0.0,234.10,317.30,1.842,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6135,4,Hurricane Ridge,2022-01-01 00:00:00,13.2,8.160,81.6,0.0,234.10,334.70,0.423,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
hurricane_ridge_2022_2.equals(hurricane_ridge_2022_1)

True